server:
  port: 8080
  #context-path: /jpa-example

security:
  basic:
    enabled: false
  user:
    name: user
    password: test

--- #구분    
    
spring:
  profiles:
    active:
    - local
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver   
    url: jdbc:mysql://localhost:3306/test_book?useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password: 1234
    hikari:
      maximum-pool-size: 10
      max-lifetime: 30  
  jpa:
#    hibernate:
#      ddl-auto: update
    show-sql: true 
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp    

logging:
  file: D:/logs/jpa-example.log
  pattern:
    file: D:/logs/jpa-example.%d{yyyy-MM-dd}.log  
    
--- #구분

spring:
  profiles: dev
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver   
    url: jdbc:mysql://192.168.0.1:3306/test?useUnicode=true&characterEncoding=utf8
    username: root
    password: 1234
    hikari:
      maximum-pool-size: 10
      max-lifetime: 30      
  jpa:
#    hibernate:
#      ddl-auto: update
    show-sql: true 
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  
logging:
 file: D:/logs_dev/jpa-example.log
 pattern:
   file: D:/logs_dev/jpa-example.%d{yyyy-MM-dd}.log  
   

    
